services:
    traefik:
        container_name: traefik_mysibsau
        image: traefik:latest
        restart: always
        ports:
            - 80:80
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./:/etc/traefik

networks:
  default:
    external: 
      name: traefik_mysibsau
